const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const A = 'http://127.0.0.1:8090';
const problemas = []; let paso = '';
function ok(c, m) { if (!c) { problemas.push('[' + paso + '] ' + m); console.log('  ✘ ' + m); } else console.log('  ✔ ' + m); }
(async () => {
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport: { width: 393, height: 851 }, isMobile: true, hasTouch: true });
  await ctx.route('**/js/config.js', r => r.fulfill({ contentType: 'application/javascript', body: 'window.CS_APP={SERVIDOR:"http://127.0.0.1:8080/tiendaonline_mongodb",TIEMPO_ESPERA_MS:8000,WHATSAPP:"573134322830"};' }));
  const p = await ctx.newPage();
  p.on('console', m => { if (m.type() === 'error') problemas.push('[' + paso + '] consola: ' + m.text()); });
  p.on('pageerror', e => problemas.push('[' + paso + '] JS: ' + e.message));
  p.on('dialog', d => d.accept());
  paso = 'splash/home';
  await p.goto(A + '/index.html');
  await p.waitForURL(/home\.html/, { timeout: 5000 });
  await p.waitForSelector('.producto-card:not(.esqueleto-card)');
  ok(await p.locator('.producto-card').count() >= 10, 'catálogo cargado desde API');
  ok(await p.locator('.categoria-btn').count() >= 5, 'categorías');
  await p.click('.categoria-btn:has-text("Techos PVC")');
  ok(await p.locator('.producto-card').count() === 2, 'filtro categoría');
  await p.click('.categoria-btn:has-text("Todas")');
  await p.fill('#buscadorProductos', 'zzzz');
  await p.waitForTimeout(300);
  ok(await p.locator('.estado-vista').count() === 1, 'estado vacío en búsqueda');
  await p.fill('#buscadorProductos', 'esmeralda');
  await p.waitForTimeout(300);
  await p.locator('.producto-card button[data-agregar]').click();
  ok(await p.locator('[data-badge-carrito]').innerText() === '1', 'agregar como invitado actualiza insignia');
  await p.locator('#cant-' + (await p.locator('[data-agregar]').getAttribute('data-agregar'))).fill('5');
  await p.locator('[data-agregar]').click();
  ok(/Solo hay 3/.test(await p.locator('.toast').innerText()), 'valida stock al agregar');
  paso = 'carrito sin sesión';
  await p.goto(A + '/pages/carrito.html');
  await p.click('#btnComprar');
  await p.waitForURL(/login\.html/);
  ok(await p.locator('#mensaje').isVisible(), 'pide iniciar sesión para comprar');
  paso = 'login';
  await p.fill('#correo', 'laura@correo.test'); await p.fill('#password', 'mala');
  await p.click('#btnLogin');
  await p.waitForSelector('#mensaje:not([hidden])');
  ok(/incorrectos/.test(await p.locator('#mensaje').innerText()), 'error de login claro');
  await p.fill('#password', 'Cliente123');
  await p.click('#btnLogin');
  await p.waitForURL(/carrito\.html/);
  ok(!!(await p.evaluate(() => localStorage.getItem('token'))), 'token guardado');
  paso = 'pago';
  await p.click('#btnComprar');
  await p.waitForURL(/pago\.html/);
  ok(/simulador/i.test(await p.locator('.pse-aviso').innerText()), 'simulador identificado');
  await p.check('input[value=rechazado]');
  await p.selectOption('#banco', { index: 1 });
  await p.click('#btnPagar');
  await p.waitForSelector('h2:has-text("Pago rechazado")');
  ok(true, 'pago rechazado sin crear pedido');
  await p.click('text=Intentar de nuevo');
  await p.check('input[value=aprobado]');
  await p.click('#btnPagar');
  await p.waitForURL(/pago_exitoso\.html/, { timeout: 10000 });
  ok(/^CS-\d{6}$/.test(await p.locator('#pedidoNumero').innerText()), 'número de pedido');
  const url = await p.evaluate(() => JSON.parse(localStorage.getItem('ultimoPedido')).comprobante_url);
  const pdf = await p.request.get(url);
  ok((await pdf.body()).slice(0, 4).toString() === '%PDF', 'comprobante firmado descarga PDF');
  const malo = await p.request.get(url.replace(/sig=[a-f0-9]+/, 'sig=00'));
  ok(malo.status() === 403, 'firma alterada rechazada');
  paso = 'pedidos';
  await p.goto(A + '/pages/pedidos.html');
  await p.waitForSelector('.pedido-card');
  ok(await p.locator('.pedido-card').count() === 2, 'solo pedidos propios (2)');
  await p.screenshot({ path: '/tmp/e2e/app_pedidos.png' });
  paso = 'api seguridad';
  const sinToken = await p.request.post('http://127.0.0.1:8080/tiendaonline_mongodb/api/api_pedidos.php', { data: { usuario_id: '000000000000000000000000' } });
  ok(sinToken.status() === 401, 'API sin token → 401');
  const legacyPdf = await p.request.get('http://127.0.0.1:8080/tiendaonline_mongodb/api/descargar_pedido_app.php?id=a&usuario_id=b');
  ok(legacyPdf.status() === 400, 'descarga sin firma bloqueada');
  paso = 'sesion expirada';
  await p.evaluate(() => localStorage.setItem('token', 'f'.repeat(64)));
  await p.goto(A + '/pages/pedidos.html');
  await p.waitForURL(/login\.html/);
  ok(/expir/i.test(await p.locator('#mensaje').innerText()), 'sesión expirada lleva al login con aviso');
  paso = 'sin servidor';
  await ctx.route('**/api/**', r => r.abort());
  await p.goto(A + '/home.html');
  await p.waitForSelector('.estado-vista, .producto-card:not(.esqueleto-card)');
  ok(await p.locator('text=Reintentar').count() === 1 || await p.locator('.producto-card').count() > 0, 'sin servidor: error o datos guardados');
  await p.screenshot({ path: '/tmp/e2e/app_home.png' });
  const w = await p.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1);
  ok(w, 'sin scroll horizontal');
  await b.close();
  console.log('PROBLEMAS: ' + problemas.length); problemas.forEach(x => console.log(x));
})().catch(e => { console.error(e); console.log(problemas.join('\n')); });
